apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-subchart
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: helm/bgd-subchart/
    repoURL: https://github.com/danialasghar/GitOps-PoC.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true