postgres:
    config:
        data:
            - key: POSTGRES_DB
              value: test
            - key: POSTGRES_USER
              value: test
            - key: POSTGRES_PASSWORD
              value: test
            - key: POSTGRES_HOST_AUTH_METHOD
              value: trust
