replicaCount: 1
postgres:
  name: helm-postgres
  group: db
  container:
    image: postgres:9.6-alpine
    port: 5432
    environment:
      POSTGRES_PASSWORD: test
      PGUSER: test
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: test
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: helm-postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /postgresql/data
    pvc:
      name: helm-postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 4Gi
  config:
    name: helm-postgres-config
    data:
       - key: key
         value: value
